version: '3.2'

services:
  test:
    build:
      context: .
    image: textbroker
    volumes:
      - ./:/app
    command: composer run test

  fixcs:
    volumes:
      - ./:/app
    image: ricc/composer-prestissimo:latest
    command: composer run fix-cs

  psysh:
    volumes:
      - ./:/app
    image: ricc/psysh:latest
